services:
  postgres:
    container_name: k8s_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
